name: flutter_base_application
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_base_libraries:
    path: ../flutter_base_libraries
  flutter_core:
    path: ../flutter_core
  ui_design_system:
    path: ../ui_design_system
  man_module:
    path: ../man_module
  pom_module:
    path: ../pom_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.10.4
  injectable_generator: ^2.9.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/
  module:
    androidX: true
    androidPackage: com.example.flutter_base_application
    iosBundleIdentifier: com.example.flutterBaseApplication

flutter_gen:
  output: lib/generated/assets_gen
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: Assets